name: geo
channels:
  - defaults
dependencies:
  - _tflow_select=2.1.0=gpu
  - absl-py=0.7.1=py36_0
  - affine=2.2.2=py36_0
  - asn1crypto=0.24.0=py36_0
  - astor=0.7.1=py36_0
  - attrs=19.1.0=py36_1
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=3.1.0=py36_0
  - bokeh=1.1.0=py36_0
  - boto3=1.9.134=py_0
  - botocore=1.12.134=py_0
  - bzip2=1.0.6=h14c3975_5
  - c-ares=1.15.0=h7b6447c_1
  - ca-certificates=2019.1.23=0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.3.9=py36_0
  - cffi=1.12.3=py36h2e261b9_0
  - click=7.0=py36_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py36_0
  - cloudpickle=0.8.1=py_0
  - cryptography=2.6.1=py36h1ba5d50_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.3.1=cuda10.0_0
  - cupti=10.0.130=0
  - curl=7.64.1=hbc83047_0
  - cycler=0.10.0=py36_0
  - cytoolz=0.9.0.1=py36h14c3975_1
  - dask=1.2.0=py_0
  - dask-core=1.2.0=py_0
  - dask-glm=0.2.0=py36_0
  - dask-ml=0.12.0=py_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.4.0=py36_1
  - defusedxml=0.6.0=py_0
  - descartes=1.1.0=py36_0
  - distributed=1.27.1=py36_0
  - docutils=0.14=py36_0
  - entrypoints=0.3=py36_0
  - expat=2.2.6=he6710b0_0
  - fiona=1.8.4=py36hc38cc03_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - freexl=1.0.5=h14c3975_0
  - gast=0.2.2=py36_0
  - gdal=2.3.3=py36hbb2a789_0
  - geopandas=0.4.1=py_0
  - geos=3.7.1=he6710b0_0
  - giflib=5.1.4=h14c3975_1
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - grpcio=1.16.1=py36hf8bcb03_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.9.0=py36h7918eee_0
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.4=hb1b8bf9_0
  - heapdict=1.0.0=py36_2
  - icu=58.2=h9c2bf20_1
  - idna=2.8=py36_0
  - imageio=2.5.0=py36_0
  - intel-openmp=2019.3=199
  - ipykernel=5.1.0=py36h39e3cac_0
  - ipython=7.5.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36_0
  - jedi=0.13.3=py36_0
  - jinja2=2.10.1=py36_0
  - jmespath=0.9.4=py_0
  - jpeg=9b=h024ee3a_2
  - json-c=0.13.1=h1bed415_0
  - jsonschema=3.0.1=py36_0
  - jupyter_client=5.2.4=py36_0
  - jupyter_core=4.4.0=py36_0
  - jupyterlab=0.35.5=py36hf63ae98_0
  - jupyterlab_server=0.2.0=py36_0
  - kealib=1.4.7=hd0c454d_6
  - keras=2.2.4=0
  - keras-applications=1.0.7=py_0
  - keras-base=2.2.4=py36_0
  - keras-preprocessing=1.0.9=py_0
  - kiwisolver=1.1.0=py36he6710b0_0
  - krb5=1.16.1=h173b8e3_7
  - libboost=1.67.0=h46d08c1_4
  - libcurl=7.64.1=h20c2e04_0
  - libdap4=3.19.1=h6ec2957_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgdal=2.3.3=h2e7e64b_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libkml=1.3.0=h590aaf7_4
  - libnetcdf=4.6.1=h11d0813_2
  - libpng=1.6.37=hbc83047_0
  - libpq=11.2=h20c2e04_0
  - libprotobuf=3.7.1=hd408876_0
  - libsodium=1.0.16=h1bed415_0
  - libspatialindex=1.8.5=h20b78c2_2
  - libspatialite=4.3.0a=hb08deb6_19
  - libssh2=1.8.2=h1ba5d50_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=he19cac6_0
  - llvmlite=0.28.0=py36hd408876_0
  - locket=0.2.0=py36_1
  - mapclassify=2.0.1=py_0
  - markdown=3.1=py36_0
  - markupsafe=1.1.1=py36h7b6447c_0
  - matplotlib=3.0.3=py36h5429711_0
  - mistune=0.8.4=py36h7b6447c_0
  - mkl=2019.3=199
  - mkl_fft=1.0.12=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - mock=2.0.0=py36_0
  - msgpack-python=0.6.1=py36hfd86e86_1
  - multipledispatch=0.6.0=py36_0
  - munch=2.3.2=py36_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py36_0
  - ncurses=6.1=he6710b0_1
  - networkx=2.3=py_0
  - nodejs=10.13.0=he6710b0_0
  - notebook=5.7.8=py36_0
  - numba=0.43.1=py36h962f231_0
  - numpy=1.16.3=py36h7e9f1db_0
  - numpy-base=1.16.3=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.1.1b=h7b6447c_1
  - packaging=19.0=py36_0
  - pandas=0.24.2=py36he6710b0_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.4.0=py_0
  - partd=0.3.10=py36_1
  - patsy=0.5.1=py36_0
  - pbr=5.1.3=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=6.0.0=py36h34e0f95_0
  - pip=19.1=py36_0
  - pixman=0.38.0=h7b6447c_0
  - poppler=0.65.0=h581218d_1
  - poppler-data=0.4.9=0
  - proj4=5.2.0=he6710b0_1
  - prometheus_client=0.6.0=py36_0
  - prompt_toolkit=2.0.9=py36_0
  - protobuf=3.7.1=py36he6710b0_0
  - psutil=5.6.2=py36h7b6447c_0
  - psycopg2=2.7.6.1=py36h1ba5d50_0
  - ptyprocess=0.6.0=py36_0
  - pycparser=2.19=py36_0
  - pygments=2.3.1=py36_0
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.4.0=py_0
  - pyproj=1.9.6=py36h14380d9_0
  - pyqt=5.9.2=py36h05f1152_2
  - pyrsistent=0.14.11=py36h7b6447c_0
  - pysal=1.14.4.post1=py36_1
  - pysocks=1.6.8=py36_0
  - python=3.6.8=h0371630_0
  - python-dateutil=2.8.0=py36_0
  - pytz=2019.1=py_0
  - pywavelets=1.0.3=py36hdd07704_1
  - pyyaml=5.1=py36h7b6447c_0
  - pyzmq=18.0.0=py36he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - rasterio=1.0.21=py36hc38cc03_0
  - readline=7.0=h7b6447c_5
  - rtree=0.8.3=py36_0
  - s3transfer=0.2.0=py36_0
  - scikit-image=0.15.0=py36he6710b0_0
  - scikit-learn=0.20.3=py36hd81dba3_0
  - scipy=1.2.1=py36h7c811a0_0
  - seaborn=0.9.0=py36_0
  - send2trash=1.5.0=py36_0
  - setuptools=41.0.1=py36_0
  - shapely=1.6.4=py36h86c5351_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.12.0=py36_0
  - snuggs=1.4.3=py_0
  - sortedcontainers=2.1.0=py36_0
  - sqlalchemy=1.3.3=py36h7b6447c_0
  - sqlite=3.28.0=h7b6447c_0
  - statsmodels=0.9.0=py36h035aef0_0
  - tblib=1.3.2=py36_0
  - tensorboard=1.13.1=py36hf484d3e_0
  - tensorflow=1.13.1=gpu_py36h3991807_0
  - tensorflow-base=1.13.1=gpu_py36h8d69cac_0
  - tensorflow-estimator=1.13.0=py_0
  - tensorflow-gpu=1.13.1=h0d30ee6_0
  - termcolor=1.1.0=py36_1
  - terminado=0.8.2=py36_0
  - testpath=0.4.2=py36_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.9.0=py36_0
  - tornado=6.0.2=py36h7b6447c_0
  - traitlets=4.3.2=py36_0
  - urllib3=1.24.2=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_1
  - werkzeug=0.15.2=py_0
  - wheel=0.33.1=py36_0
  - xerces-c=3.2.2=h780794e_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.3.1=he6710b0_3
  - zict=0.1.4=py36_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - atomicwrites==1.3.0
    - cartopy==0.17.0
    - chardet==3.0.4
    - contextily==0.99.0
    - geographiclib==1.49
    - geojson==2.4.1
    - geomet==0.2.0.post2
    - geopy==1.19.0
    - html2text==2018.1.9
    - mercantile==1.0.4
    - more-itertools==7.0.0
    - opencv-python==4.1.0.25
    - pluggy==0.9.0
    - py==1.8.0
    - pyshp==2.1.0
    - pytest==4.4.0
    - rasterstats==0.13.1
    - requests==2.21.0
    - sentinelsat==0.13
    - simplejson==3.16.0
    - tqdm==4.31.1
    - xgboost==0.82

